name: CI/CD-Pipeline-to-AWS-express-app-hb
env:
  EB_PACKAGE_S3_BUCKET_NAME: "express-app-hb"
  EB_APPLICATION_NAME: "express-app-hb"
  EB_ENVIRONMENT_NAME: "Expressapphb-env"
  DEPLOY_PACKAGE_NAME: "express_app_hb_${{ github.sha }}.zip"
  AWS_REGIN_NAME: "us-west-2"

on:
  # Triggers the workflow on push events only for the "master" branch
  push:
    branches:
      - master

jobs:
  ci-part:
    runs-on: ubuntu-latest

    steps:
      - name: Git Clone My Repo
        uses: actions/checkout@v1

      - name: Create ZIP deployment package
        run : zip -r ${{ env.DEPLOY_PACKAGE_NAME }} ./ -x *.git* ./node_modules/*






