name: my-GitHubActions
env:
  APPLICATION_NAME: "My Express-app-hb"
  DEPLOY_PACKAGE_NAME    : "Deploy-ver-${{ github.sha }}"

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
   my-testing:
     runs-on: ubuntu-latest

     steps:
     - name: Print Hello Message
       run : echo "Hello world from testing"

     - name: Execute few commands
       run : |
        echo "Message 1"
        echo "Message 2"  
        echo "Application name: ${{ env.APPLICATION_NAME }}"  

     - name: Git Clone My Repo
       uses: actions/checkout@v1

     - name: List of Project
       run : ls -la

   my-deploy:
     runs-on: ubuntu-latest
     needs: [my-testing]

     steps:
     - name: Print Hello Message
       run : echo "Hello world from deploy"



